config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/teapot:
      branch: main
      repo: https://github.com/interTwin-eu/teapot
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-mauve-penguin.sh
        container: qc.acc_gimpy-orchid-orangutan
  QC.Doc:
    repos:
      github.com/interTwin-eu/teapot find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-zucchini-walrus.sh
        container: qc.doc_stinky-chestnut-uakari
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-dandelion-blue.sh
        container: qc.doc_homey-buff-alligator
      github.com/interTwin-eu/teapot markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-blue-ostrich.sh
        container: qc.doc_queasy-cinnabar-capybara
  QC.Lic:
    repos:
      github.com/interTwin-eu/teapot licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-flax-insect.sh
        container: qc.lic_wimpy-sepia-woodpecker
  QC.Sec:
    repos:
      github.com/interTwin-eu/teapot bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-amethyst-starfish.sh
        container: qc.sec_ugly-vermilion-dunker
  QC.Sty:
    repos:
      github.com/interTwin-eu/teapot flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pink-akita.sh
        container: qc.sty_lousy-brass-quetzal
      github.com/interTwin-eu/teapot hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-magnolia-whippet.sh
        container: qc.sty_tacky-alizarin-caracal
      github.com/interTwin-eu/teapot jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-gold-salamander.sh
        container: qc.sty_homely-malachite-boar
  QC.Uni:
    repos:
      github.com/interTwin-eu/teapot pytest:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-olive-retriever.sh
        container: qc.uni_lanky-razzmatazz-chamois
  QC.Ver:
    repos:
      github.com/interTwin-eu/teapot get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amber-setter.sh
        container: qc.ver_snippy-charcoal-fox
timeout: 5400
