config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/teapot:
      branch: main
      repo: https://github.com/interTwin-eu/teapot
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lilac-vole.sh
        container: qc.acc_sickly-wheat-spaniel
  QC.Doc:
    repos:
      github.com/interTwin-eu/teapot find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-maroon-wolverine.sh
        container: qc.doc_crabby-ecru-greyhound
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-olivine-uguisu.sh
        container: qc.doc_snappy-cobalt-earwig
  QC.Lic:
    repos:
      github.com/interTwin-eu/teapot licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-wisteria-earwig.sh
        container: qc.lic_wiggy-cerise-starfish
  QC.Ver:
    repos:
      github.com/interTwin-eu/teapot get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-chartreuse-gibbon.sh
        container: qc.ver_jumpy-russet-mouse
timeout: 5400
