config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/teapot:
      branch: main
      repo: https://github.com/interTwin-eu/teapot
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-aqua-avocet.sh
        container: qc.acc_gummy-purple-elephant
  QC.Doc:
    repos:
      github.com/interTwin-eu/teapot find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-charcoal-jellyfish.sh
        container: qc.doc_sloppy-khaki-bandicoot
      github.com/interTwin-eu/teapot git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-rust-birman.sh
        container: qc.doc_crabby-eggplant-octopus
      github.com/interTwin-eu/teapot markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-crimson-hummingbird.sh
        container: qc.doc_queasy-cerise-emu
  QC.Lic:
    repos:
      github.com/interTwin-eu/teapot licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-tomato-wolf.sh
        container: qc.lic_thirsty-ochre-ferret
  QC.Met:
    repos:
      github.com/interTwin-eu/teapot cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ultramarine-newfoundland.sh
        container: qc.met_bluesy-azure-zorse
  QC.Sec:
    repos:
      github.com/interTwin-eu/teapot bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-orchid-tang.sh
        container: qc.sec_pasty-ultramarine-havanese
  QC.Sty:
    repos:
      github.com/interTwin-eu/teapot flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-eggplant-owl.sh
        container: qc.sty_lumpy-amethyst-binturong
      github.com/interTwin-eu/teapot hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mustard-spider.sh
        container: qc.sty_wheezy-magnolia-squirt
      github.com/interTwin-eu/teapot jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-coral-antelope.sh
        container: qc.sty_slaphappy-indigo-beagle
  QC.Uni:
    repos:
      github.com/interTwin-eu/teapot pytest:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-heliotrope-harrier.sh
        container: qc.uni_tacky-sepia-tortoise
  QC.Ver:
    repos:
      github.com/interTwin-eu/teapot get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-magenta-barnacle.sh
        container: qc.ver_greasy-champagne-mist
timeout: 5400
